# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ios.xdc

# Block Designs: bd/minimal/minimal.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==minimal || ORIG_REF_NAME==minimal} -quiet] -quiet

# IP: bd/minimal/ip/minimal_c_counter_binary_0_1/minimal_c_counter_binary_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==minimal_c_counter_binary_0_1 || ORIG_REF_NAME==minimal_c_counter_binary_0_1} -quiet] -quiet

# IP: bd/minimal/ip/minimal_tft_ili9341_wrapper_0_0/minimal_tft_ili9341_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==minimal_tft_ili9341_wrapper_0_0 || ORIG_REF_NAME==minimal_tft_ili9341_wrapper_0_0} -quiet] -quiet

# XDC: /home/jeremiah/Programming/FPGA/Vivado/MicroPhaseZ7_Lite_Minimal/MicroPhaseZ7_Lite_Minimal.gen/sources_1/bd/minimal/minimal_ooc.xdc
